- id: "pubmed:39111315"
  image: "https://ars.els-cdn.com/content/image/1-s2.0-S1074761324003522-fx1.jpg"
  tags:
    - "genomics"
    - "transcriptomics"
    - "cancer"
    - "immunity"
    - "TME"

- id: "pubmed:23682826"
  image: "https://cdn.ncbi.nlm.nih.gov/pmc/blobs/0046/3662649/53f774f82d61/1471-2164-14-336-3.jpg"
  tags:
    - "breast cancer"
    - "classification"
    - "single cell"
    - "gene expression signature"
    - "statistical method"

- id: "pubmed:34115745"
  image: "https://cdn.ncbi.nlm.nih.gov/pmc/blobs/1b82/8221796/8fb0565b0a4d/pcbi.1008944.g001.jpg"
  tags:
    - "cancer"
    - "tumor heterogeneity"
    - "statistical method"

- id: "pubmed:29666255"
  image: "https://www.pnas.org/cms/10.1073/pnas.1721628115/asset/1429c0a2-879a-4178-8867-dcb9cd7f7dd8/assets/graphic/pnas.1721628115fig01.jpeg"
  tags:
    - "cancer"
    - "tumor heterogeneity"
    - "statistical method"

- id: "pubmed:23880963"
  image: "https://cdn.ncbi.nlm.nih.gov/pmc/blobs/1d82/3883768/24594ab2add1/epi-8-907-g1.jpg"
  tags:
    - "prostate cancer"
    - "epigenetics"
    - "combination therapy"
    - "gene expression"

- id: "pubmed:32079618"
  image: "https://genome.cshlp.org/content/30/7/1073/F1.large.jpg"
  tags:
    - "genomics"
    - "transcriptomics"
    - "long non-coding RNA"
    - "FANTOM"
    - "gene expression"

- id: "pubmed:38191471"
  image: "https://cdn.ncbi.nlm.nih.gov/pmc/blobs/1519/10774315/4938ab239bd1/41467_2023_44210_Fig1_HTML.jpg"
  tags:
    - "prostate cancer"
    - "TME"
    - "single cell"
    - "spatial transcriptomics"

- id: "pubmed:39272208"
  image: "https://media.springernature.com/full/springer-static/image/art%3A10.1186%2Fs13058-024-01876-9/MediaObjects/13058_2024_1876_Fig1_HTML.png"
  tags:
    - "breast cancer"
    - "hormone signaling"
    - "gene expression signature"

- id: "pubmed:38016949"
  image: "https://cdn.ncbi.nlm.nih.gov/pmc/blobs/9a46/10684511/91e0cd125e1e/41467_2023_43651_Fig1_HTML.jpg"
  tags:
    - "method"
    - "structural variants"

- id: "pubmed:37964363"
  image: "https://cdn.ncbi.nlm.nih.gov/pmc/blobs/0342/10647131/e40db7c7b497/12967_2023_4713_Fig1_HTML.jpg"
  tags:
    - "method"
    - "structural variants"

- id: "pubmed:37409050"
  image: "https://cdn.ncbi.nlm.nih.gov/pmc/blobs/a612/10318336/a4365e60c675/fx1.jpg"
  tags:
    - "method"
    - "genetics"

- id: "doi:10.1016/j.isci.2023.106108"
  title: "Using biological constraints to improve prediction in precision oncology."
  image: "https://www.cell.com/cms/10.1016/j.isci.2023.106108/asset/a5a2122a-2006-41b9-9430-b28bd10251fc/main.assets/fx1_lrg.jpg"
  tags:
    - "method"
    - "machine learning"
    - "overfitting"

- id: "doi:10.1111/ajt.17174"
  title: "Donor-derived acute myeloid leukemia in solid organ transplantation."
  image: "https://www.amjtransplant.org/cms/10.1111/ajt.17174/asset/6adfb962-a336-407e-857e-e13b1f5b5244/main.assets/gr1_lrg.jpg"
  tags:
    - "transplantation"
    - "acute myeloid leukemia"
    - "cancer"
    - "clonal hematopoiesis"

- id: "doi:10.1172/JCI171164"
  title: "YAP1 induces bladder cancer progression and promotes immune evasion through IL-6/STAT3 pathway and CXCL deregulation."
  image: "https://dm5migu4zj3pb.cloudfront.net/manuscripts/171000/171164/medium/JCI171164.ga.jpg"
  tags:
    - "bladder cancer"
    - "immunotherapy"
    - "signaling dysregulation"

- id: "doi:10.1101/2024.08.30.24312735"
  title: "Gene Signature for Predicting Metastasis in Prostate Cancer Using Primary Tumor Expression Profiles."
  image: "https://www.medrxiv.org/content/medrxiv/early/2024/08/31/2024.08.30.24312735/F1.large.jpg"
  tags:
    - "prostate cancer"
    - "progression"
    - "metastasis"
    - "gene expression"

- id: "doi:10.1038/s44287-023-00012-7"
  title: "Gene Signature for Predicting Metastasis in Prostate Cancer Using Primary Tumor Expression Profiles."
  image: "images/science/aiForPath.jpg"
  tags:
    - "review"
    - "digital pathology"
    - "artificial intelligence"
    - "machine learning"
    - "algorithm"

- id: "pubmed:36525970"
  image: "https://www.cell.com/cms/10.1016/j.ccell.2022.11.016/asset/43045ec7-86f2-46ce-9a93-40f7f6b89849/main.assets/fx1_lrg.jpg"
  tags:
    - "cancer"
    - "TME"
    - "colorectal cancer"

- id: "pubmed:38987117"
  image: "https://www.thelancet.com/cms/asset/ce72b56e-2606-4f96-bef7-2a85b273a892/cov200h.gif"
  tags:
    - "review"
    - "digital pathology"
    - "artificial intelligence"
    - "machine learning"
    - "algorithm"

- id: "pubmed:38831751"
  image: "https://www.ncbi.nlm.nih.gov/corecgi/tileshop/tileshop.fcgi?p=PMC3&id=447942&s=188&r=3&c=2"

- id: "pubmed:36717286"
  image: "https://cdn.ncbi.nlm.nih.gov/pmc/blobs/6ee5/10192088/254c6650b5e6/nihms-1870452-f0001.jpg"

- id: "pubmed:36204675"
  image: "https://f1000research.s3.amazonaws.com/manuscripts/134369/5377ac7f-9085-4d2a-920c-b469056be8be_figure1.gif"

- id: "pubmed:39294134"
  image: "https://cdn.ncbi.nlm.nih.gov/pmc/blobs/af4f/11411086/225ca71832bd/41467_2024_51924_Fig2_HTML.jpg"
  tags:
    - "covid19"
    - "sars"
    - "SARS-CoV-2"
    - "RNA sequencing"

- id: "pubmed:38253539"
  image: "https://cdn.ncbi.nlm.nih.gov/pmc/blobs/0890/10803790/0982ed7369fc/41525_2024_392_Fig1_HTML.jpg"

- id: "pubmed:38706981"
  image: "https://cdn.ncbi.nlm.nih.gov/pmc/blobs/01eb/11068064/55e30235a388/nihms-1940400-f0001.jpg"

- id: "pubmed:39630608"
  image: "https://dm5migu4zj3pb.cloudfront.net/manuscripts/171000/171164/medium/JCI171164.ga.jpg"

- id: "pubmed:36282572"
  image: "https://dm5migu4zj3pb.cloudfront.net/manuscripts/160000/160767/medium/JCI160767.ga.jpg"
  tags:
    - "cancer"
    - "lymphoma"

- id: "pubmed:31804462"
  image: "https://cdn.ncbi.nlm.nih.gov/pmc/banners/logo-cddis.gif"
  tags:
    - "review"
    - "computational biology"
    - "collaborative science"
    
- id: "pubmed:34618807"
  image: "https://journals.plos.org/plosbiology/article/figure/image?size=large&id=10.1371/journal.pbio.3001419.g003"
  tags:
    - "review"
    - "computational biology"
    - "collaboration"

- id: "pubmed:32718982"
  image: "https://cdn.ncbi.nlm.nih.gov/pmc/blobs/941c/7397864/877a7874f0c1/1060f01.jpg"
  tags:
    - "genome architecture"
    - "long non-coding RNA"
    - "antisense"
    - "FANTOM"

- id: "pubmed:38862340"
  image: "https://ars.els-cdn.com/content/image/1-s2.0-S2588931124001421-gr1.jpg"

- id: "pubmed:39094629"
  image: "https://media.springernature.com/w316/springer-static/cover-hires/journal/66"
  tags:
    - "post-trancriptional regulation"
    - "cancer"
    - "prostate cancer"
    - "radioterapy"
    - "metastasis"
    - "ROBIN"

- id: "pubmed:36759904"
  image: "https://cdn.ncbi.nlm.nih.gov/pmc/blobs/381b/9912678/2411f65028a2/13059_2023_2865_Fig1_HTML.jpg"
  tags:
    - "post-trancriptional regulation"
    - "splicing"
    - "cancer"
    - "genomics"
    - "transcriptomics"
    - "method"
 
- id: "pubmed:35979657"
  image: "https://cdn.ncbi.nlm.nih.gov/pmc/blobs/f438/9897593/c932219972b9/nihms-1837110-f0005.jpg"
  tags:
    - "acute myeloid leukemia"
    - "transplantation"
    - "genomics"
    - "cancer"
    - "clonal hematopoiesis"

- id: "pubmed:37034687"
  image: "https://www.ncbi.nlm.nih.gov/core/lw/2.0/html/tileshop_pmc/tileshop_pmc_inline.html?title=Click%20on%20image%20to%20zoom&p=PMC3&id=10081210_nihpp-2023.03.29.534769v1-f0001.jpg"

- id: "pubmed:32718981"
  image: "https://genome.cshlp.org/content/30/7/951/F1.large.jpg"
  tags:
    - "FANTOM"
    - "gene expression"
    - "genome"
    - "evolution"

- id: "pubmed:38284821"
  image: "https://cdn.ncbi.nlm.nih.gov/pmc/blobs/f06b/10985477/8971a4b3b864/347fig1.jpg"

- id: "pubmed:36543879"
  image: "https://www.researchgate.net/publication/43352174/figure/fig2/AS:280319287676947@1443844734580/Clonal-origination-and-evolution-in-myeloproliferative-neoplasms-MPNs-PV-polycythemia.png"

- id: "pubmed:33396819"
  image: "https://cdn.ncbi.nlm.nih.gov/pmc/blobs/4172/7823382/7056f98fb721/metabolites-11-00020-g001.jpg"
  tags:
    - "cancer"
    - "metabolism"
    - ""

- id: "pubmed:36852282"
  image: "https://ars.els-cdn.com/content/image/1-s2.0-S2589004223001852-fx1.jpg"
  tags:
    - "cancer"
    - "tumor heterogeneity"
    - "statistical method"

- id: "pubmed:38946967"
  image: "https://cdn.ncbi.nlm.nih.gov/pmc/blobs/af4f/11411086/225ca71832bd/41467_2024_51924_Fig2_HTML.jpg"
  tags:
    - "covid19"
    - "sars"
    - "SARS-CoV-2"
    - "RNA sequencing"

- id: "pubmed:18252678"
  image: "https://www.acpjournals.org/cms/10.7326/0003-4819-148-5-200803040-00208/asset/images/7ff1.jpg"
  tags:
    - "review"
    - "breast cancer"
    - "gene expression"
    - "prediction"

- id: "pubmed:25575134"
  image: "https://cdn.ncbi.nlm.nih.gov/pmc/blobs/0c21/4357229/6daf0cf37d7b/nihms642970f1.jpg"
  tags:
    - "Notch"
    - "cancer"

- id: "pubmed:38157646"
  image: "https://ars.els-cdn.com/content/image/1-s2.0-S0008874923X00094-cov200h.gif"

- id: "pubmed:37812042"
  image: "https://onlinelibrary.wiley.com/cms/asset/3b985041-f153-4742-92d4-7a033939eb67/pros24629-fig-0001-m.png"

- id: "pubmed:18457476"
  image: "https://www.ncbi.nlm.nih.gov/corehtml/pmc/pmcgifs/bookshelf/thumbs/th-erta160-lrg.png"
  tags:
    - "review"
    - "gene expression"
    - "breast cancer"
    - "prediction"

- id: "pubmed:33991092"
  image: "https://cdn.ncbi.nlm.nih.gov/pmc/blobs/f92e/8122363/7822da1e156c/baab027f1.jpg"
  tags:
    - "resource"
    - "covid19"
    - "SARS-CoV-2"

- id: "pubmed:34297428"
  image: "https://cdn.ncbi.nlm.nih.gov/pmc/blobs/9ebd/8713532/ae6177296d9c/BPA-32-e13007-g005.jpg"

- id: "pubmed:26862087"
  image: "https://cdn.ncbi.nlm.nih.gov/pmc/blobs/05e4/4818686/27fc0f97bbb5/nihms759794f1.jpg"
  tags:
    - "cancer"

- id: "pubmed:34311724"
  image: "https://cdn.ncbi.nlm.nih.gov/pmc/blobs/309d/8314517/e2ff49d2a74c/12885_2021_8593_Fig1_HTML.jpg"
  tags:
    - "prostate cancer"
    - "PTEN"
    - "gene expression"

- id: "pubmed:39510141"
  image: "https://www.thegreenjournal.com/cms/10.1016/j.radonc.2024.110618/asset/46e8dc12-dc11-4fef-ab32-f93a821536b4/main.assets/gr1.jpg"
  tags:
    - "prostate cancer"
    - "cancer"
    - "radiotherapy"
    - "ROBIN"

- id: "pubmed:28411178"
  image: "https://cdn.ncbi.nlm.nih.gov/pmc/blobs/2a38/5628161/2dcb1eb3f674/nihms902381f1.jpg"
  tags:
    - "cancer"
    - "renal cell carcinoma"
    - "microRNA"
    - "gene expression"
    - "gene fusion"

- id: "pubmed:34746025"
  image: "https://images-provider.frontiersin.org/api/ipx/w=410&f=webp/https://www.frontiersin.org/files/Articles/743616/fcimb-11-743616-HTML/image_m/fcimb-11-743616-g002.jpg"
  tags:
    - "prediction"
    - "malaria"
    - "gene expression"

- id: "pubmed:36752203"
  image: "https://cdn.ncbi.nlm.nih.gov/pmc/blobs/5c35/9977441/0a4cd9e39d85/jciinsight-8-162409-g117.jpg"

- id: "pubmed:32607525"

- id: "pubmed:38016949"
  image: "https://cdn.ncbi.nlm.nih.gov/pmc/blobs/9a46/10684511/91e0cd125e1e/41467_2023_43651_Fig1_HTML.jpg"
  tags:
    - "method"
    - "cancer"

- id: "pubmed:32817372"

- id: "pubmed:29180467"

- id: "pubmed:33923159"

- id: "pubmed:36038558"

- id: "pubmed:34880124"

- id: "pubmed:37419704"
  image: "https://ars.els-cdn.com/content/image/X22132945.jpg"

- id: "pubmed:24086345"

- id: "pubmed:36122486"

- id: "pubmed:33819273"
  image: "https://cdn.ncbi.nlm.nih.gov/pmc/blobs/1cc9/8021195/4749a0e92fd5/pone.0249002.g003.jpg"
  tags:
    - "method"
    - "genomics"
    - "transcriptomics"
    - "heterogeneity"

- id: "pubmed:31360735"

- id: "pubmed:30181298"

- id: "pubmed:30655325"

- id: "pubmed:33568675"

- id: "pubmed:37216914"
  image: "https://cdn.ncbi.nlm.nih.gov/pmc/blobs/c39a/10250081/9c5aaaa435e8/btad333f1.jpg"

- id: "pubmed:26062848"

- id: "pubmed:25354783"

- id: "pubmed:26542228"

- id: "pubmed:25864518"

- id: "pubmed:29684357"

- id: "pubmed:35634961"

- id: "pubmed:34569064"

- id: "pubmed:26422827"

- id: "pubmed:28038920"

- id: "pubmed:32366326"

- id: "pubmed:22960283"

- id: "pubmed:28561063"

- id: "pubmed:37693379"
  image: "https://cdn.ncbi.nlm.nih.gov/pmc/blobs/c09e/10491133/d54b5bc661dc/nihpp-2023.08.28.555119v1-f0001.jpg"

- id: "pubmed:28174896"

- id: "pubmed:24486590"

- id: "pubmed:21421236"

- id: "pubmed:22018358"

- id: "pubmed:26109417"

- id: "pubmed:24403532"

- id: "pubmed:14707141"

- id: "pubmed:29739972"

- id: "pubmed:30339629"

- id: "pubmed:22761195"

- id: "pubmed:33408119"

- id: "pubmed:29467463"

- id: "pubmed:32410671"

- id: "pubmed:22585994"

- id: "pubmed:21512138"

- id: "pubmed:20664052"

- id: "pubmed:21360566"

- id: "pubmed:29396848"

- id: "pubmed:30518628"

- id: "pubmed:27799525"

- id: "pubmed:38721890"
  image: "https://onlinelibrary.wiley.com/cms/asset/0c5d16ce-d050-444a-a61e-ba95421b6790/cyto.b.v106.4.cover.jpg"

- id: "pubmed:20488783"

- id: "pubmed:39252915"
  image: "https://www.medrxiv.org/content/medrxiv/early/2024/08/31/2024.08.30.24312735/F1.large.jpg"
  tags:
    - "prostate cancer"
    - "progression"
    - "metastasis"
    - "gene expression"

- id: "pubmed:29568059"

- id: "pubmed:25535351"

- id: "pubmed:27334595"

- id: "pubmed:22313051"

- id: "pubmed:24086249"

- id: "pubmed:31502941"

- id: "pubmed:21703415"

- id: "pubmed:21176082"

- id: "pubmed:23452820"

- id: "pubmed:23161775"

- id: "pubmed:26374070"

- id: "pubmed:30171262"

- id: "pubmed:19544456"

- id: "pubmed:28811253"

- id: "pubmed:22527098"

- id: "pubmed:23515613"

- id: "pubmed:21562231"

- id: "pubmed:25262153"

- id: "pubmed:24786473"

- id: "pubmed:29980786"

- id: "pubmed:29704674"

- id: "pubmed:26058959"

- id: "pubmed:23760244"

- id: "pubmed:28692661"

- id: "pubmed:27683042"

- id: "pubmed:30777857"

- id: "pubmed:27401248"

- id: "pubmed:26446945"

- id: "pubmed:20585447"

- id: "pubmed:26230923"

- id: "pubmed:26599435"

- id: "pubmed:21169257"

- id: "pubmed:29340028"

- id: "pubmed:27376138"

- id: "pubmed:22927397"

- id: "pmc:PMC2821899"

- id: "pubmed:23434645"

- id: "pubmed:29262631"

- id: "pubmed:31557666"

- id: "pubmed:24703100"

- id: "pubmed:19695104"

- id: "pubmed:15377994"

- id: "pubmed:14744102"

- id: "pubmed:28437440"

    
    
    
