- id: "pubmed:39111315"
  image: "https://ars.els-cdn.com/content/image/1-s2.0-S1074761324003522-fx1.jpg"
  tags:
    - cancer
    - immunity
    - TME

- id: "pubmed:23682826"
  image: "https://cdn.ncbi.nlm.nih.gov/pmc/blobs/0046/3662649/53f774f82d61/1471-2164-14-336-3.jpg"
  tags:
    - "breast cancer"
    - classification
    - "single cell"
    - "gene expression signature"
    - "statistical method"

- id: "pubmed:34115745"
  image: "https://cdn.ncbi.nlm.nih.gov/pmc/blobs/1b82/8221796/8fb0565b0a4d/pcbi.1008944.g001.jpg"
  tags:
    - cancer
    - "tumor heterogeneity"
    - "statistical method"

- id: "pubmed:29666255"
  image: "https://www.pnas.org/cms/10.1073/pnas.1721628115/asset/1429c0a2-879a-4178-8867-dcb9cd7f7dd8/assets/graphic/pnas.1721628115fig01.jpeg"
  tags:
    - cancer
    - "tumor heterogeneity"
    - "statistical method"

- id: "pubmed:23880963"
  image: "https://cdn.ncbi.nlm.nih.gov/pmc/blobs/1d82/3883768/24594ab2add1/epi-8-907-g1.jpg"
  tags:
    - "prostate cancer"
    - "epigenetics"
    - "combination therapy"
    - "gene expression"


