- id: "pubmed:39111315"
  image: "https://ars.els-cdn.com/content/image/1-s2.0-S1074761324003522-fx1.jpg"
  tags:
    - cancer
    - immunity
    - TME
- id: "pubmed:38191471"
  image: "https://media.springernature.com/lw685/springer-static/image/art%3A10.1038%2Fs41467-023-44210-1/MediaObjects/41467_2023_44210_Fig1_HTML.png"
  tags:
    - prostate cancer
    - TME
    - "single cell"
    - "spatial transcriptomics"
- id: "pubmed:36852282"
  image: "https://ars.els-cdn.com/content/image/1-s2.0-S2589004223001852-fx1.jpg"
  tags:
    - cancer
    - "tumor heterogeneity"
    - "statistical method"
- id: "pubmed:34115745"
  image: "https://cdn.ncbi.nlm.nih.gov/pmc/blobs/1b82/8221796/8fb0565b0a4d/pcbi.1008944.g001.jpg"
  tags:
    - cancer
    - "tumor heterogeneity"
    - "statistical method"
- id: "pubmed:29666255"
  image: "https://www.pnas.org/cms/10.1073/pnas.1721628115/asset/1429c0a2-879a-4178-8867-dcb9cd7f7dd8/assets/graphic/pnas.1721628115fig01.jpeg"
  tags:
    - cancer
    - "tumor heterogeneity"
    - "statistical method"
- id: "pmc:PMC2821899"
